spring:
  application:
    name: spring-feignclient
server:
 port: 1260
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9999/eureka/
    
    